### ISSUE TITLE
Ability to add an extra cycle to a session

### ISSUE THREAD

**Issue by ElijahLynn** [Ultraworking/headquarters#3]
One thing I really love about the spreadsheet is that if I am on a roll and want to keep going, I can just add another cycle to my session. I don't see a way to do this with Headquarters right now and therefore I still prefer the spreadsheet to the app. 

Can we add feature to be able to add a cycle after the session has started?

**Comment by leeknowlton** [comment]
Thanks for bringing this up @ElijahLynn 
Will certainly work on the UX flow for this, but it is possible: https://www.loom.com/share/78e4bc4dbef7458ba129d497e8a186c2

**Comment by ElijahLynn** [comment]
Oh nice, didn't realize that was a workaround! I'll give that a try!
